services:
  db:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: lukascorbitt
      POSTGRES_PASSWORD: password
      POSTGRES_DB: yuri_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  api:
    build:
      context: ./api
    container_name: api
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=lukascorbitt
      - DB_PASSWORD=password
      - DB_NAME=yuri_development
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app_network
    command: >
      sh -c "npm run docker:dev"

  client:
    build:
      context: ./client
    container_name: client
    ports:
      - "3001:3001"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
    networks:
      - app_network
    command: ["npm", "start"]

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
